language: node_js
sudo: false
node_js:
  - "0.12"
addons:
  apt:
    packages:
      - libboost-all-dev
      - libboost-chrono1.48-dev
before_install:
  - git config --global user.email "dev@bitpay.com"
  - git config --global user.name "BitPay, Inc."
